[project]
name = "jarvis"
version = "0.0.1"
description = "Stark Industries JARVIS"
authors = [{name = "Andrew Morris"}]
requires-python = ">=3.11"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
]

dependencies = [
    "jarvis-core",
    "jarvis-app"
]

[tool.uv.workspace]
members = [
    ".",
    "packages/*",
    "packages/modules",
    "packages/modules/*/*"
]

[tool.uv]
managed = true
package = false

[tool.uv.sources]
jarvis-core = { workspace = true }
jarvis-app = { workspace = true }
